# Generated by Django 4.2.13 on 2024-06-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerAutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('clase', models.CharField(max_length=50)),
                ('anio_fabricacion', models.PositiveIntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('direccion_agencia', models.CharField(max_length=50)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.BooleanField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_compra', models.DateField()),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('estrellas', models.IntegerField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.BooleanField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_compra', models.DateField()),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.BooleanField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_compra', models.DateField()),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerolinea', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=6)),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.BooleanField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_compra', models.DateField()),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
