# Generated by Django 4.2.13 on 2024-07-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_alquilerautos_reserva_remove_hoteles_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traslados',
            name='hora',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='hora',
            field=models.CharField(max_length=4),
        ),
    ]
