from django import forms

class VueloForm(forms.Form):
    aerolinea      = forms.CharField(max_length=50, required=True)
    mail           = forms.EmailField(required=True)
    numero         = forms.CharField(max_length=6, required=True)
    origen         = forms.CharField(max_length=50, required=True)
    destino        = forms.CharField(max_length=50, required=True)
    fecha          = forms.DateField(required=True)
    hora           = forms.CharField(max_length=4,required=True)
    precio         = forms.DecimalField(max_digits=10,decimal_places=2, required=True)
    fecha_reserva  = forms.DateField()
    fecha_compra   = forms.DateField()
    usuario        = forms.CharField(max_length=50)

class HotelForm(forms.Form):
    nombre         = forms.CharField(max_length=50, required=True)
    mail           = forms.EmailField(required=True)
    ciudad         = forms.CharField(max_length=50, required=True)
    pais           = forms.CharField(max_length=50, required=True)
    direccion      = forms.CharField(max_length=60, required=True)
    estrellas      = forms.IntegerField(required=True)
    fecha_desde    = forms.DateField(required=True)
    fecha_hasta    = forms.DateField(required=True)
    precio         = forms.DecimalField(max_digits=10,decimal_places=2, required=True)
    fecha_reserva  = forms.DateField()
    fecha_compra   = forms.DateField()
    usuario        = forms.CharField(max_length=50)
    
class TrasladoForm(forms.Form):
    nombre         = forms.CharField(max_length=50, required=True)
    mail           = forms.EmailField(required=True)
    ciudad         = forms.CharField(max_length=50, required=True)
    pais           = forms.CharField(max_length=50, required=True)
    origen         = forms.CharField(max_length=50, required=True)
    destino        = forms.CharField(max_length=50, required=True)
    fecha          = forms.DateField(required=True)
    hora           = forms.CharField(max_length=4,required=True)
    precio         = forms.DecimalField(max_digits=10,decimal_places=2, required=True)
    fecha_reserva  = forms.DateField()
    fecha_compra   = forms.DateField()
    usuario        = forms.CharField(max_length=50)

class AlquilerautoForm(forms.Form):
    nombre            = forms.CharField(max_length=50, required=True)
    mail              = forms.EmailField(required=True)
    clase             = forms.CharField(max_length=50, required=True)
    anio_fabricacion  = forms.IntegerField(required=True)
    ciudad            = forms.CharField(max_length=50, required=True)
    pais              = forms.CharField(max_length=50, required=True)
    direccion_agencia = forms.CharField(max_length=50, required=True)
    fecha_desde       = forms.DateField(required=True)
    fecha_hasta       = forms.DateField(required=True)
    precio            = forms.DecimalField(max_digits=10,decimal_places=2, required=True)
    fecha_reserva     = forms.DateField()
    fecha_compra      = forms.DateField()
    usuario           = forms.CharField(max_length=50)